# Project: 跑步
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = 跑步.o
LINKOBJ  = 跑步.o
LIBS     = -L"D:/2.dev c++/Dev-Cpp/MinGW64/lib" -L"D:/2.dev c++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"D:/2.dev c++/Dev-Cpp/MinGW64/include" -I"D:/2.dev c++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/2.dev c++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/2.dev c++/Dev-Cpp/MinGW64/include" -I"D:/2.dev c++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/2.dev c++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/2.dev c++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 跑步.exe
CXXFLAGS = $(CXXINCS) -g3 -std=c++11
CFLAGS   = $(INCS) -g3 -std=c++11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

跑步.o: 跑步.cpp
	$(CPP) -c 跑步.cpp -o 跑步.o $(CXXFLAGS)
